### ISSUE TITLE
PC specifications in the Terminal

### ISSUE THREAD

**Issue by PandaTheProgrammer** [Xithrius/TODO#1]
How about a PC TUI which shows the following:

1. Temperatures of the CPU and the GPU
2. Memory Usage
3. Storage used across all drives
4. PC specifications 

I am looking to make something of this sort but I am VERY new to rust and would love to have an open source project that I can use and observe.

**Comment by Xithrius** [comment]
What about the `neofetch` command?

**Comment by PandaTheProgrammer** [comment]
What about windows systems? Your terminal projects do work in them?

**Comment by Xithrius** [comment]
Ah, so a cross-OS system monitor. I shall add that to the list. Thanks!

**Comment by PandaTheProgrammer** [comment]
Yes

**Comment by Xithrius** [comment]
Very well.

**Comment by Xithrius** [comment]
Done.
